[package]
name = "worker"
version = "0.1.0"
edition = "2021"

[dependencies]
common-lib = { path = "../../common" }
futures-util = "0.3.31"
redis = { version = "0.29.1", features = ["tokio-comp"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
